### ISSUE TITLE
欢迎提xf-tts-socket的bug

### ISSUE THREAD

**Issue by jimuyouyou** [itiwll/network-rc#1]
你好！https://www.npmjs.com/package/xf-tts-socket 是我包装的支持async-await的讯飞语音合成库。以前都是我自己在用，非常开心你的项目中能用到。如果使用过程中有问题，可以直接给我提issue，谢谢！

**Comment by jimuyouyou** [comment]
讯飞本身是支持pcm格式的，我看你源码里边专门用ffmpeg从mp3转成了pcm.可以这样稍微调整下：
const business = {aue: 'pcm'}; // sfl这个参数不用传输了，他是mp3专用
const file = 'test.pcm';

**Comment by itiwll** [comment]
> 你好！https://www.npmjs.com/package/xf-tts-socket 是我包装的支持async-await的讯飞语音合成库。以前都是我自己在用，非常开心你的项目中能用到。如果使用过程中有问题，可以直接给我提issue，谢谢！

感谢你的 xf-tts-socket
